[workspace]
resolver = "2"
members = [
  "helper",
  "day-01",
  "day-02",
  "day-03",
  "day-04",
]

[workspace.package]
version = "1.0.0"
edition = "2021"


[workspace.dependencies]
itertools = "0.12.0"
helper = { path = "./helper" }